### PR TITLE
Avoid CMAKE_BUILD_TYPE warnings on Windows.

### PR DESCRIPTION
**Pull request by Blast545**
Fixes https://ci.ros2.org/view/nightly/job/nightly_win_rel/1639/msbuild/ Introduced with https://github.com/ros2/ros2/pull/985#issuecomment-663610669

Signed-off-by: Michel Hidalgo <michel@ekumenlabs.com>

### CODE REVIEW

**Comment by Blast545** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11623/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6756/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9508/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11598/)

**Comment by Blast545** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/11624/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6757/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/9509/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11598/)

**Comment by Blast545** [comment]
Build type Release, as the nightly that caused the error.

* Windows [Build Status](http://ci.ros2.org/job/ci_windows/11601/)

**Review by hidmic — APPROVED** [review]
LGTM !

**Pull request merged**
