### PR TITLE
Update to the commit that fixes the executable stack.

### PR DESCRIPTION
**Pull request by clalancette**
See https://github.com/ros2/Mimick/pull/26 for more information.

Still a draft since I need to test out the aarch64 changes in CI.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19204/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13762/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19943/)

**Comment by clalancette** [comment]
Here is clang and RHEL as well:

* RHEL [Build Status](http://ci.ros2.org/job/ci_linux-rhel/455/)
* Clang [Build Status](http://ci.ros2.org/job/ci_linux_clang_libcxx/27/)

**Comment by clalancette** [comment]
OK, ros2/Mimick#26 has been merged, and I've now updated this one to point to the head of that repository.  So this should be good to go for a review and merge.

**Comment by clalancette** [comment]
And one more CI just to check that I didn't mess up the hash:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/19264/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13806/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19994/)

**Review by cottsay — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
