### PR TITLE
Update to latest commit on fork for Apple M1 support

### PR DESCRIPTION
**Pull request by christophebedard**
See https://github.com/ros2/Mimick/pull/17

Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>

### CODE REVIEW

**Comment by ros-discourse** [comment]
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/m1-mac-feasibility/20369/7

**Review by hidmic — APPROVED** [review]
LGTM pending green CI.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14626/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9381/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12292/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14767/)

**Comment by christophebedard** [comment]
@hidmic thanks for the review!

I don't think the CI run is testing my branch unfortunately :grin:

```yaml
  ros2/mimick_vendor:
    type: git
    url: https://github.com/ros2/mimick_vendor.git
    version: master
```

https://gist.githubusercontent.com/hidmic/42b8db51e3c2590a585b484add081ac6/raw/f882bf42a33af552ed9201033d7247028c3abb7a/ros2.repos

**Comment by christophebedard** [comment]
CI with this branch:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/14636/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/9390/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/12301/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/14781/)

**Comment by hidmic** [comment]
> I don't think the CI run is testing my branch unfortunately grin

Ouch. I thought I had posted the right modified `ros2.repos` -- I clearly did not. 

Thanks for the catch and for re-running CI @christophebedard!

**Pull request merged**
