### PR TITLE
Update to the commit that includes DT_GNU_HASH.

### PR DESCRIPTION
**Pull request by clalancette**
This is just the PR that updates the hash corresponding to https://github.com/ros2/Mimick/pull/36 .  See that PR for the details.

Note that once that PR is merged, the hash here will have to be updated.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21157/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15461/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21883/)

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
All right, I've merged in the other PR.  I'll update this one to the correct hash, and then re-run CI.

**Comment by clalancette** [comment]
New CI:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21185/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15491/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21907/)

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
Sorry, didn't mean to merge... I will keep an eye and if CI comes back yellow/red I will revert.

**Comment by fujitatomoya** [comment]
@clalancette @ahcorde can we backport this to jazzy? i have been meeting this issue, e.g https://github.com/ros2/rclcpp/pull/2542

**Comment by ahcorde** [comment]
https://github.com/Mergifyio backport jazzy

**Pull request merged**
