### PR TITLE
Also export include directories

### PR DESCRIPTION
**Pull request by brawner**
Signed-off-by: Stephen Brawner <brawner@gmail.com>

### CODE REVIEW

**Comment by brawner** [comment]
Testing with rcutils commit (https://github.com/ros2/rcutils/commit/21820e86c06ce0e7ec025fdf35971a979ebedac7), and this branch of mimick_vendor, `--packages-select rcutils mimick_vendor`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13165/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8096/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10881/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13173/)

**Comment by brawner** [comment]
Building succeeds with the rcutils commit, but it does generate a warning about `literal.h` having an unused parameter. That warning won't be introduced with this PR so it's ok. But it should be addressed in a followup PR anyway.

**Comment by hidmic** [comment]
> That warning won't be introduced with this PR so it's ok. But it should be addressed in a followup PR anyway.

Agreed.

**Review by hidmic — APPROVED** [review]
LGTM!

**Pull request merged**
